# Generated by Django 5.2.6 on 2025-10-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
