# Generated by Django 5.2.6 on 2025-10-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_asistencia_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_empleados/', verbose_name='Foto de Perfil'),
        ),
    ]
